---
platform: linux

image_resource:
  type: docker-image
  source: {repository: aeons/elixir-gcc, tag: "1.4.1"}

inputs:
- name: src-phx-bench
- name: version

outputs:
- name: build-artifact

run:
  path: ./src-phx-bench/elixir_phoenix_bench/scripts/build.sh
  args:
  - src-phx-bench/elixir_phoenix_bench
