---
platform: linux

image_resource:
  type: docker-image
  source: {repository: aeons/elixir-gcc:1.4.1}

inputs:
- name: src-phx-bench

outputs:
- name: _build/dev/rel/phx_bench_api/releases/0.0.1/phx_bench_api.tar.gz

run:
  path: scripts/build.sh
  dir: src-phx-bench
