jobs:
- name: build-phx-bench
  public: true
  serial: true
  plan:
  - get: src-phx-bench
  - task: build
    file: src-phx-bench/elixir_phoenix_bench/tasks/build.yml
  - task: unit-test
    file: src-phx-bench/elixir_phoenix_bench/tasks/unit-test.yml
  - task: integration-test
    file: src-phx-bench/elixir_phoenix_bench/tasks/integration-test.yml
  - put: phx-bench-docker-image
    get_params: {skip_download: true}
    params:
      build: rel-artifacts

resources:
- name: src-phx-bench
  type: git
  source:
    uri: https://github.com/cackharot/benchmarks.git
    branch: master
    paths: [elixir_phoenix_bench]

- name: phx-bench-docker-image
  type: docker-image
  source:
    repository: 13.127.47.6:30400/testing/phx_bench
    tag: debug
    insecure_registries:
      - "13.127.47.6:30400"
